/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/common';
import * as i2 from './modal-header';
import * as i3 from './modal';
const styles_BsModalHeaderComponent:any[] = ([] as any[]);
export const RenderType_BsModalHeaderComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_BsModalHeaderComponent,data:{}});
function View_BsModalHeaderComponent_1(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),4,'button',[['aria-label',
      'Dismiss'],['class','close'],['type','button']],(null as any),[[(null as any),
      'click']],(_v,en,$event) => {
    var ad:boolean = true;
    var _co:any = _v.component;
    if (('click' === en)) {
      const pd_0:any = ((<any>_co.modal.dismiss()) !== false);
      ad = (pd_0 && ad);
    }
    return ad;
  },(null as any),(null as any))),(_l()(),i0.ɵted(-1,(null as any),['\n                '])),
      (_l()(),i0.ɵeld(2,0,(null as any),(null as any),1,'span',[['aria-hidden','true']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted(-1,(null as any),['×'])),(_l()(),i0.ɵted(-1,(null as any),['\n            ']))],
      (null as any),(null as any));
}
export function View_BsModalHeaderComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted(-1,(null as any),['\n        '])),(_l()(),i0.ɵeld(1,
      0,(null as any),(null as any),6,'div',[['class','modal-header']],(null as any),
      (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted(-1,
      (null as any),['\n            '])),(_l()(),i0.ɵand(16777216,(null as any),(null as any),
      1,(null as any),View_BsModalHeaderComponent_1)),i0.ɵdid(4,16384,(null as any),
      0,i1.NgIf,[i0.ViewContainerRef,i0.TemplateRef],{ngIf:[0,'ngIf']},(null as any)),
      (_l()(),i0.ɵted(-1,(null as any),['\n            '])),i0.ɵncd((null as any),
          0),(_l()(),i0.ɵted(-1,(null as any),['\n        '])),(_l()(),i0.ɵted(-1,
          (null as any),['\n    ']))],(_ck,_v) => {
    var _co:i2.BsModalHeaderComponent = _v.component;
    const currVal_0:any = _co.showDismiss;
    _ck(_v,4,0,currVal_0);
  },(null as any));
}
export function View_BsModalHeaderComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'bs-modal-header',
      ([] as any[]),(null as any),(null as any),(null as any),View_BsModalHeaderComponent_0,
      RenderType_BsModalHeaderComponent)),i0.ɵdid(1,49152,(null as any),0,i2.BsModalHeaderComponent,
      [i3.BsModalComponent],(null as any),(null as any))],(null as any),(null as any));
}
export const BsModalHeaderComponentNgFactory:i0.ComponentFactory<i2.BsModalHeaderComponent> = i0.ɵccf('bs-modal-header',
    i2.BsModalHeaderComponent,View_BsModalHeaderComponent_Host_0,{showDismiss:'showDismiss'},
    {},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3BhdHJpY2svZGV2L25nMi1iczMtbW9kYWwvc3JjL25nMi1iczMtbW9kYWwvbW9kYWwvbW9kYWwtaGVhZGVyLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL3BhdHJpY2svZGV2L25nMi1iczMtbW9kYWwvc3JjL25nMi1iczMtbW9kYWwvbW9kYWwvbW9kYWwtaGVhZGVyLnRzIiwibmc6Ly8vVXNlcnMvcGF0cmljay9kZXYvbmcyLWJzMy1tb2RhbC9zcmMvbmcyLWJzMy1tb2RhbC9tb2RhbC9tb2RhbC1oZWFkZXIudHMuQnNNb2RhbEhlYWRlckNvbXBvbmVudC5odG1sIiwibmc6Ly8vVXNlcnMvcGF0cmljay9kZXYvbmcyLWJzMy1tb2RhbC9zcmMvbmcyLWJzMy1tb2RhbC9tb2RhbC9tb2RhbC1oZWFkZXIudHMuQnNNb2RhbEhlYWRlckNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgICAgICA8ZGl2IGNsYXNzPVwibW9kYWwtaGVhZGVyXCI+XG4gICAgICAgICAgICA8YnV0dG9uICpuZ0lmPVwic2hvd0Rpc21pc3NcIiB0eXBlPVwiYnV0dG9uXCIgY2xhc3M9XCJjbG9zZVwiIGFyaWEtbGFiZWw9XCJEaXNtaXNzXCIgKGNsaWNrKT1cIm1vZGFsLmRpc21pc3MoKVwiPlxuICAgICAgICAgICAgICAgIDxzcGFuIGFyaWEtaGlkZGVuPVwidHJ1ZVwiPiZ0aW1lczs8L3NwYW4+XG4gICAgICAgICAgICA8L2J1dHRvbj5cbiAgICAgICAgICAgIDxuZy1jb250ZW50PjwvbmctY29udGVudD5cbiAgICAgICAgPC9kaXY+XG4gICAgIiwiPGJzLW1vZGFsLWhlYWRlcj48L2JzLW1vZGFsLWhlYWRlcj4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7O29CQ0VZO01BQUE7TUFBQTtJQUFBO0lBQUE7SUFBNkU7TUFBQTtNQUFBO0lBQUE7SUFBN0U7RUFBQSxnQ0FBdUc7TUFDbkc7VUFBQTtNQUF5Qix5Q0FBYzs7OztvQkFIdkQsa0RBQ1E7TUFBQTtNQUFBLDBEQUEwQjtNQUFBLG1DQUN0QjtNQUFBLHVEQUFBO01BQUE7TUFFUyw2REFDVDtVQUFBLEdBQXlCLGtEQUN2QjtVQUFBOztJQUpNO0lBQVIsV0FBUSxTQUFSOzs7O29CQ0ZaO01BQUE7dUNBQUEsVUFBQTtNQUFBOzs7OyJ9
