/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/common';
import * as i2 from './modal-footer';
import * as i3 from './modal';
const styles_BsModalFooterComponent:any[] = ([] as any[]);
export const RenderType_BsModalFooterComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_BsModalFooterComponent,data:{}});
function View_BsModalFooterComponent_1(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'button',[['class',
      'btn btn-default'],['type','button']],(null as any),[[(null as any),'click']],
      (_v,en,$event) => {
        var ad:boolean = true;
        var _co:any = _v.component;
        if (('click' === en)) {
          const pd_0:any = ((<any>_co.modal.dismiss()) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },(null as any),(null as any))),(_l()(),i0.ɵted(1,(null as any),['\n                ',
      '\n            ']))],(null as any),(_ck,_v) => {
    var _co:any = _v.component;
    const currVal_0:any = _co.dismissButtonLabel;
    _ck(_v,1,0,currVal_0);
  });
}
function View_BsModalFooterComponent_2(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'button',[['class',
      'btn btn-primary'],['type','button']],(null as any),[[(null as any),'click']],
      (_v,en,$event) => {
        var ad:boolean = true;
        var _co:any = _v.component;
        if (('click' === en)) {
          const pd_0:any = ((<any>_co.modal.close()) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },(null as any),(null as any))),(_l()(),i0.ɵted(1,(null as any),['\n                ',
      '\n              ']))],(null as any),(_ck,_v) => {
    var _co:any = _v.component;
    const currVal_0:any = _co.closeButtonLabel;
    _ck(_v,1,0,currVal_0);
  });
}
export function View_BsModalFooterComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted(-1,(null as any),['\n        '])),(_l()(),i0.ɵeld(1,
      0,(null as any),(null as any),9,'div',[['class','modal-footer']],(null as any),
      (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted(-1,
      (null as any),['\n            '])),i0.ɵncd((null as any),0),(_l()(),i0.ɵted(-1,
      (null as any),['\n            '])),(_l()(),i0.ɵand(16777216,(null as any),(null as any),
      1,(null as any),View_BsModalFooterComponent_1)),i0.ɵdid(6,16384,(null as any),
      0,i1.NgIf,[i0.ViewContainerRef,i0.TemplateRef],{ngIf:[0,'ngIf']},(null as any)),
      (_l()(),i0.ɵted(-1,(null as any),['\n            '])),(_l()(),i0.ɵand(16777216,
          (null as any),(null as any),1,(null as any),View_BsModalFooterComponent_2)),
      i0.ɵdid(9,16384,(null as any),0,i1.NgIf,[i0.ViewContainerRef,i0.TemplateRef],
          {ngIf:[0,'ngIf']},(null as any)),(_l()(),i0.ɵted(-1,(null as any),['\n        '])),
      (_l()(),i0.ɵted(-1,(null as any),['\n    ']))],(_ck,_v) => {
    var _co:i2.BsModalFooterComponent = _v.component;
    const currVal_0:any = _co.showDefaultButtons;
    _ck(_v,6,0,currVal_0);
    const currVal_1:any = _co.showDefaultButtons;
    _ck(_v,9,0,currVal_1);
  },(null as any));
}
export function View_BsModalFooterComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'bs-modal-footer',
      ([] as any[]),(null as any),(null as any),(null as any),View_BsModalFooterComponent_0,
      RenderType_BsModalFooterComponent)),i0.ɵdid(1,49152,(null as any),0,i2.BsModalFooterComponent,
      [i3.BsModalComponent],(null as any),(null as any))],(null as any),(null as any));
}
export const BsModalFooterComponentNgFactory:i0.ComponentFactory<i2.BsModalFooterComponent> = i0.ɵccf('bs-modal-footer',
    i2.BsModalFooterComponent,View_BsModalFooterComponent_Host_0,{showDefaultButtons:'showDefaultButtons',
        dismissButtonLabel:'dismissButtonLabel',closeButtonLabel:'closeButtonLabel'},
    {},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3BhdHJpY2svZGV2L25nMi1iczMtbW9kYWwvc3JjL25nMi1iczMtbW9kYWwvbW9kYWwvbW9kYWwtZm9vdGVyLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL3BhdHJpY2svZGV2L25nMi1iczMtbW9kYWwvc3JjL25nMi1iczMtbW9kYWwvbW9kYWwvbW9kYWwtZm9vdGVyLnRzIiwibmc6Ly8vVXNlcnMvcGF0cmljay9kZXYvbmcyLWJzMy1tb2RhbC9zcmMvbmcyLWJzMy1tb2RhbC9tb2RhbC9tb2RhbC1mb290ZXIudHMuQnNNb2RhbEZvb3RlckNvbXBvbmVudC5odG1sIiwibmc6Ly8vVXNlcnMvcGF0cmljay9kZXYvbmcyLWJzMy1tb2RhbC9zcmMvbmcyLWJzMy1tb2RhbC9tb2RhbC9tb2RhbC1mb290ZXIudHMuQnNNb2RhbEZvb3RlckNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgICAgICA8ZGl2IGNsYXNzPVwibW9kYWwtZm9vdGVyXCI+XG4gICAgICAgICAgICA8bmctY29udGVudD48L25nLWNvbnRlbnQ+XG4gICAgICAgICAgICA8YnV0dG9uICpuZ0lmPVwic2hvd0RlZmF1bHRCdXR0b25zXCIgdHlwZT1cImJ1dHRvblwiIGNsYXNzPVwiYnRuIGJ0bi1kZWZhdWx0XCIgKGNsaWNrKT1cIm1vZGFsLmRpc21pc3MoKVwiPlxuICAgICAgICAgICAgICAgIHt7ZGlzbWlzc0J1dHRvbkxhYmVsfX1cbiAgICAgICAgICAgIDwvYnV0dG9uPlxuICAgICAgICAgICAgPGJ1dHRvbiAqbmdJZj1cInNob3dEZWZhdWx0QnV0dG9uc1wiIHR5cGU9XCJidXR0b25cIiBjbGFzcz1cImJ0biBidG4tcHJpbWFyeVwiIChjbGljayk9XCJtb2RhbC5jbG9zZSgpXCI+XG4gICAgICAgICAgICAgICAge3tjbG9zZUJ1dHRvbkxhYmVsfX1cbiAgICAgICAgICAgICAgPC9idXR0b24+XG4gICAgICAgIDwvZGl2PlxuICAgICIsIjxicy1tb2RhbC1mb290ZXI+PC9icy1tb2RhbC1mb290ZXI+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7OztvQkNHWTtNQUFBO01BQUE7UUFBQTtRQUFBO1FBQXlFO1VBQUE7VUFBQTtRQUFBO1FBQXpFO01BQUEsZ0NBQW1HO01BQUE7O0lBQUE7SUFBQTs7OztvQkFHbkc7TUFBQTtNQUFBO1FBQUE7UUFBQTtRQUF5RTtVQUFBO1VBQUE7UUFBQTtRQUF6RTtNQUFBLGdDQUFpRztNQUFBOztJQUFBO0lBQUE7Ozs7b0JBTjdHLGtEQUNRO01BQUE7TUFBQSwwREFBMEI7TUFBQSwwQ0FDdEIsa0JBQXlCO01BQUEsbUNBQ3pCO01BQUEsdURBQUE7TUFBQTtNQUVTLHNEQUNUO1VBQUE7YUFBQTtVQUFBLGlDQUVXO01BQ1Q7O0lBTk07SUFBUixXQUFRLFNBQVI7SUFHUTtJQUFSLFdBQVEsU0FBUjs7OztvQkNOWjtNQUFBO3VDQUFBLFVBQUE7TUFBQTs7Ozs7In0=
