/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './modal-body';
const styles_BsModalBodyComponent:any[] = ([] as any[]);
export const RenderType_BsModalBodyComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_BsModalBodyComponent,data:{}});
export function View_BsModalBodyComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted(-1,(null as any),['\n        '])),(_l()(),i0.ɵeld(1,
      0,(null as any),(null as any),3,'div',[['class','modal-body']],(null as any),
      (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted(-1,
      (null as any),['\n            '])),i0.ɵncd((null as any),0),(_l()(),i0.ɵted(-1,
      (null as any),['\n        '])),(_l()(),i0.ɵted(-1,(null as any),['\n    ']))],
      (null as any),(null as any));
}
export function View_BsModalBodyComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'bs-modal-body',
      ([] as any[]),(null as any),(null as any),(null as any),View_BsModalBodyComponent_0,
      RenderType_BsModalBodyComponent)),i0.ɵdid(1,49152,(null as any),0,i1.BsModalBodyComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const BsModalBodyComponentNgFactory:i0.ComponentFactory<i1.BsModalBodyComponent> = i0.ɵccf('bs-modal-body',
    i1.BsModalBodyComponent,View_BsModalBodyComponent_Host_0,{},{},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3BhdHJpY2svZGV2L25nMi1iczMtbW9kYWwvc3JjL25nMi1iczMtbW9kYWwvbW9kYWwvbW9kYWwtYm9keS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9wYXRyaWNrL2Rldi9uZzItYnMzLW1vZGFsL3NyYy9uZzItYnMzLW1vZGFsL21vZGFsL21vZGFsLWJvZHkudHMiLCJuZzovLy9Vc2Vycy9wYXRyaWNrL2Rldi9uZzItYnMzLW1vZGFsL3NyYy9uZzItYnMzLW1vZGFsL21vZGFsL21vZGFsLWJvZHkudHMuQnNNb2RhbEJvZHlDb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL3BhdHJpY2svZGV2L25nMi1iczMtbW9kYWwvc3JjL25nMi1iczMtbW9kYWwvbW9kYWwvbW9kYWwtYm9keS50cy5Cc01vZGFsQm9keUNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgICAgICA8ZGl2IGNsYXNzPVwibW9kYWwtYm9keVwiPlxuICAgICAgICAgICAgPG5nLWNvbnRlbnQ+PC9uZy1jb250ZW50PlxuICAgICAgICA8L2Rpdj5cbiAgICAiLCI8YnMtbW9kYWwtYm9keT48L2JzLW1vZGFsLWJvZHk+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7b0JDQUEsa0RBQ1E7TUFBQTtNQUFBLDBEQUF3QjtNQUFBLDBDQUNwQixrQkFBeUI7TUFBQSwrQkFDdkI7Ozs7b0JDSGQ7TUFBQTtxQ0FBQSxVQUFBO01BQUE7OzsifQ==
