/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/common';
import * as i2 from './modal';
import * as i3 from './modal-service';
const styles_BsModalComponent:any[] = ([] as any[]);
export const RenderType_BsModalComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_BsModalComponent,data:{}});
export function View_BsModalComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted(-1,(null as any),['\n        '])),(_l()(),i0.ɵeld(1,
      0,(null as any),(null as any),7,'div',[['class','modal-dialog']],(null as any),
      (null as any),(null as any),(null as any),(null as any))),i0.ɵdid(2,278528,(null as any),
      0,i1.NgClass,[i0.IterableDiffers,i0.KeyValueDiffers,i0.ElementRef,i0.Renderer],
      {klass:[0,'klass'],ngClass:[1,'ngClass']},(null as any)),(_l()(),i0.ɵted(-1,
      (null as any),['\n            '])),(_l()(),i0.ɵeld(4,0,(null as any),(null as any),
      3,'div',[['class','modal-content']],(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i0.ɵted(-1,(null as any),['\n                '])),
      i0.ɵncd((null as any),0),(_l()(),i0.ɵted(-1,(null as any),['\n            '])),
      (_l()(),i0.ɵted(-1,(null as any),['\n        '])),(_l()(),i0.ɵted(-1,(null as any),
          ['\n    ']))],(_ck,_v) => {
    var _co:i2.BsModalComponent = _v.component;
    const currVal_0:any = 'modal-dialog';
    const currVal_1:any = _co.getCssClasses();
    _ck(_v,2,0,currVal_0,currVal_1);
  },(null as any));
}
export function View_BsModalComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'bs-modal',([] as any[]),
      [[2,'fade',(null as any)],[2,'modal',(null as any)],[1,'role',0],[1,'tabindex',
          0]],(null as any),(null as any),View_BsModalComponent_0,RenderType_BsModalComponent)),
      i0.ɵdid(1,4964352,(null as any),0,i2.BsModalComponent,[i0.ElementRef,i3.BsModalService,
          i0.NgZone],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(_ck,_v) => {
    const currVal_0:any = i0.ɵnov(_v,1).fadeClass;
    const currVal_1:any = i0.ɵnov(_v,1).modalClass;
    const currVal_2:any = i0.ɵnov(_v,1).roleAttr;
    const currVal_3:any = i0.ɵnov(_v,1).tabindexAttr;
    _ck(_v,0,0,currVal_0,currVal_1,currVal_2,currVal_3);
  });
}
export const BsModalComponentNgFactory:i0.ComponentFactory<i2.BsModalComponent> = i0.ɵccf('bs-modal',
    i2.BsModalComponent,View_BsModalComponent_Host_0,{animation:'animation',backdrop:'backdrop',
        keyboard:'keyboard',size:'size',cssClass:'cssClass'},{onShow:'onShow',onOpen:'onOpen',
        onHide:'onHide',onClose:'onClose',onDismiss:'onDismiss',onLoaded:'onLoaded'},
    ['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3BhdHJpY2svZGV2L25nMi1iczMtbW9kYWwvc3JjL25nMi1iczMtbW9kYWwvbW9kYWwvbW9kYWwubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvcGF0cmljay9kZXYvbmcyLWJzMy1tb2RhbC9zcmMvbmcyLWJzMy1tb2RhbC9tb2RhbC9tb2RhbC50cyIsIm5nOi8vL1VzZXJzL3BhdHJpY2svZGV2L25nMi1iczMtbW9kYWwvc3JjL25nMi1iczMtbW9kYWwvbW9kYWwvbW9kYWwudHMuQnNNb2RhbENvbXBvbmVudC5odG1sIiwibmc6Ly8vVXNlcnMvcGF0cmljay9kZXYvbmcyLWJzMy1tb2RhbC9zcmMvbmcyLWJzMy1tb2RhbC9tb2RhbC9tb2RhbC50cy5Cc01vZGFsQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gICAgICAgIDxkaXYgY2xhc3M9XCJtb2RhbC1kaWFsb2dcIiBbbmdDbGFzc109XCJnZXRDc3NDbGFzc2VzKClcIj5cbiAgICAgICAgICAgIDxkaXYgY2xhc3M9XCJtb2RhbC1jb250ZW50XCI+XG4gICAgICAgICAgICAgICAgPG5nLWNvbnRlbnQ+PC9uZy1jb250ZW50PlxuICAgICAgICAgICAgPC9kaXY+XG4gICAgICAgIDwvZGl2PlxuICAgICIsIjxicy1tb2RhbD48L2JzLW1vZGFsPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQUEsa0RBQ1E7TUFBQTtNQUFBLGlFQUFBO01BQUE7TUFBQSx5REFBc0Q7TUFBQSxtQ0FDbEQ7TUFBQTtNQUFBLDhCQUEyQjthQUN2QixrQkFBeUI7TUFDdkIsa0RBQ0o7VUFBQTs7SUFKRDtJQUFxQjtJQUExQixXQUFLLFVBQXFCLFNBQTFCOzs7O29CQ0RSO01BQUE7VUFBQTthQUFBO21CQUFBO0lBQUE7O0lBQUE7SUFBQTtJQUFBO0lBQUE7SUFBQSxXQUFBLHVDQUFBOzs7Ozs7OyJ9
